# Name that will appear in the body of the email
$reportname = "Veeam Server - Report Last 24h of backup"

# SMTP Settings
$smtpServer = "smtp.office365.com"           # SMTP Server
$smtpPort   = 587                            # SMTP Port (ex: 587 for TLS/SSL)
$from       = "noreply@email.com"            # Email sender
$subject    = "Veeam - Backup Status Report" # Email subject

# List of recipients
$mailRecipient = @(
    "you@email.com",
    "aaa@email.com",
    "bbb@email.com"
)

# Sender email credentials
$smtpUsername = "noreply@email.com"
$smtpPassword = "password"

# Path and name of the report generated by the veeam-report.ps1 script to add it as an attachment
$File = "D:\Report\Veeam - Report Last 24h of backup_$(Get-Date -format dd-MM-yyyy).pdf"

# HTML mail body
$htmlBody = @"
<!DOCTYPE html>
<html lang="pt">
<head>
  <meta charset="UTF-8">
  <title>$subject</title>
</head>
<body>
  <table>
    <tbody>
      <tr>
        <td>
          <table style="width: 100%; background-color: rgb(2, 106, 179) !important;" cellspacing="0">
            <tbody>
              <tr>
                <td style="color: #fff !important; padding: 11px; font-size: 22px;">
                  Veeam Backup &amp; Replication
                </td>
              </tr>
            </tbody>
          </table>
        </td>
      </tr>
      <tr>
        <td>
          <table cellspacing="0">
            <tbody>
              <tr>
                <td style="color: rgb(136, 136, 136) !important; font-size: 14px; padding: 16px 0 0;">
                  Report name:
                </td>
              </tr>
              <tr>
                <td style="color: rgb(68, 68, 68) !important; font-size: 18px; padding: 4px 0 0;">
                  $reportname
                </td>
              </tr>
              <tr>
                <td style="color: rgb(68, 68, 68) !important; font-size: 14px; padding: 4px 0 0;">
                  $(Get-Date -format g)
                </td>
              </tr>
            </tbody>
          </table>
        </td>
      </tr>
      <tr>
        <td>
          <table style="width: 100%;" border="0" cellspacing="0">
            <tbody>
              <tr>
                <td style="width: 70%;">
                  <table cellspacing="0">
                    <tbody>
                      <tr>
                        <td style="color: rgb(136, 136, 136) !important; padding: 16px 0 0; font-size: 14px;">
                          Description:
                        </td>
                      </tr>
                      <tr>
                        <td style="color: rgb(68, 68, 68) !important; font-size: 14px; padding: 4px 0 0;">
                          This report provides information about the latest Veeam Backup &amp; Replication job statuses.
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </td>
              </tr>
            </tbody>
          </table>
        </td>
      </tr>
      <tr style="height: 1px;">
        <td>
          <div style="height: 10px; width: 100%;" aria-hidden="true">&nbsp;</div>
        </td>
      </tr>
      <tr>
        <td>
          <table style="width: 100%; height: 100%; font-size: 12pt;" cellspacing="0">
            <tbody>
              <tr>
                <td style="width: 30%; color: rgb(103, 122, 130) !important;">
                  Please see generated report in attachment.
                </td>
              </tr>
            </tbody>
          </table>
        </td>
      </tr>
    </tbody>
  </table>
</body>
</html>
"@

# Create the MailMessage object 
$mailMessage = New-Object System.Net.Mail.MailMessage
$mailMessage.From = $from

# Add each recipient to the mail
foreach ($mailRecipient in $destinatarios) {
    $mailMessage.To.Add($mailRecipient)
}

$mailMessage.Subject = $subject
$mailMessage.Body = $htmlBody
$mailMessage.IsBodyHtml = $true

# Creates the attachment object and adds it to the email
$attachment = New-Object System.Net.Mail.Attachment $File
$mailMessage.Attachments.Add($attachment)

# Configure SmtpClient with SSL and credentials
$smtpClient = New-Object System.Net.Mail.SmtpClient($smtpServer, $smtpPort)
$smtpClient.EnableSsl = $true
$smtpClient.Credentials = New-Object System.Net.NetworkCredential($smtpUsername, $smtpPassword)

# Send the email
$smtpClient.Send($mailMessage)